---
title: "Overview Map"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GitHub Documents

This is an R Markdown format used for publishing markdown documents to GitHub. When you click the **Knit** button all R code chunks are run and a markdown file (.md) suitable for publishing to GitHub is generated.

## Including Code

You can include R code in the document as follows:
```{r,echo=FALSE}
library(leaflet)
library(sf)

```

```{r}
wd=getwd()

files1<-"C:/Users/oc3512/Documents/ArcGIS/Projects/MMSP/MMSP.gdb"
files2<-"C:/Users/oc3512/Documents/ArcGIS/Projects/MMSP/MMSP(20181005).gdb"

# Check layers in the gdb
layers1<-st_layers(files1)
layers2<-st_layers(files2)

# Read stations and main lines
stations<-st_read(files2,layers2$name[1])
ml<-st_read(files2,layers2$name[2])
depot<-st_read(files2,layers2$name[4])
ml_noZ<-st_zm(ml,drop=TRUE,what="ZM")
ML<-as(ml_noZ,"Spatial")

esri <- grep("^Esri", providers, value = TRUE)
esri<-c(esri,"MtbMap","Stamen.TonerLines","Stamen.TonerLabels")

## Base codes
m <- leaflet() %>% 
  addAwesomeMarkers(data=stations,label=~as.character(stations$Name),group="Stations",
                    labelOptions=labelOptions(noHide=TRUE,textOnly=TRUE)) %>%
  addScaleBar(position="bottomleft") %>%
  addMiniMap(tiles=esri[[1]],zoomLevelOffset = -5,toggleDisplay = TRUE, position="bottomright") %>%
  addPolylines(data=ML,group="Main Line")
```


